### ISSUE TITLE
Automatically force OAuth authorization for the user "me"

### ISSUE THREAD

**Issue by Enak-Nalla** [henrikfroehling/Trakt.NET#596]
### Failure description?

Hello,

I have verified that the client `Authorization.AccessToken` is valid, I am able to send other oauth requests.

However, `Users.GetWatchedShowsAsync("me", new TraktExtendedInfo { Full = true });`

Throws the error `TraktNet.Exceptions.TraktAuthorizationException: Unauthorized - OAuth must be provided`

Is there anything I am missing?

Thanks.

### Version

1.3.0 (Latest)

### Relevant Stacktrace

fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      TraktNet.Exceptions.TraktAuthorizationException: Unauthorized - OAuth must be provided
         at TraktNet.Requests.Handler.ResponseErrorHandler.HandleUnauthorizedError(ResponseErrorParameters errorParameters)
         at TraktNet.Requests.Handler.ResponseErrorHandler.HandleErrorsAsync(ResponseErrorParameters errorParameters, CancellationToken cancellationToken)
         at TraktNet.Requests.Handler.ResponseErrorHandler.InternalHandleErrorsAsync(ExtendedHttpRequestMessage requestMessage, HttpResponseMessage responseMessage, Boolean isCheckinRequest, Boolean isDeviceRequest, Boolean isInAuthorizationPolling, Boolean isAuthorizationRequest, Boolean isAuthorizationRevoke, CancellationToken cancellationToken)
         at TraktNet.Requests.Handler.RequestHandler.ExecuteRequestAsync(ExtendedHttpRequestMessage requestMessage, Boolean isCheckinRequest, CancellationToken cancellationToken)
         at TraktNet.Requests.Handler.RequestHandler.QueryListAsync[TResponseContentType](ExtendedHttpRequestMessage requestMessage, CancellationToken cancellationToken)
         at TraktNet.Requests.Handler.RequestHandler.ExecuteListRequestAsync[TResponseContentType](IRequest`1 request, CancellationToken cancellationToken)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by henrikfroehling** [comment]
Hello @Enak-Nalla,

good catch with this bug.
Since the [API Endpoint](https://trakt.docs.apiary.io/#reference/users/watched/get-watched) states OAuth as optional, but the user `me` always needs valid OAuth authorization, this is currently an unhandled case in the library.

Did you try the request with setting `client.Configuration.ForceAuthorization = true`?
This would be the workaround, since the library doesn't force OAuth by default, if it is stated as optional in the Trakt API.

**Comment by Enak-Nalla** [comment]
Setting `client.Configuration.ForceAuthorization = true` works, however Show.Seasons is null even with `new TraktExtendedInfo { Full = true }`

According to the documentation season information should be returned?

**Comment by henrikfroehling** [comment]
@Enak-Nalla What does the property `WatchedSeasons` say? Is it also null?
`ITraktWatchedShow` inherits from `ITraktShow`.
`ITraktShow` has the property `Seasons` which is meant as the seasons a show has to offer.
And `ITraktWwatchedShow` has the property `WatchedSeasons` which is meant as the seasons a user has already watched.
I confess this is a bit confusing, but won't be changed until version 2.0.0.

**Comment by Enak-Nalla** [comment]
Seems to be a me issue that one, The library seems to format the response differently. If we look at the response straight from the api the property is `seasons` but on the library it is `watchedSeasons`. My bad. Thanks for the help :)

**Comment by henrikfroehling** [comment]
You're welcome. Glad it works now.
