### ISSUE TITLE
Bad Request when adding items to a list

### ISSUE THREAD

**Issue by TheUltimateC0der** [henrikfroehling/Trakt.NET#62]
Although I fixed https://github.com/henrikfroehling/Trakt.NET/issues/61 temporary for myself, the request fails with the following error:

```
TraktNet.Exceptions.TraktBadRequestException
Bad Request - request couldn't be parsed

TraktNet.Exceptions.TraktBadRequestException: Bad Request - request couldn't be parsed
   at TraktNet.Requests.Handler.ResponseErrorHandler.HandleBadRequestError(ResponseErrorParameters errorParameters) in D:\Sourcecode\Github\Trakt.NET\Source\Lib\Trakt.NET\Requests\Handler\ResponseErrorHandler.cs:line 304
   at TraktNet.Requests.Handler.ResponseErrorHandler.HandleErrorsAsync(ResponseErrorParameters errorParameters, CancellationToken cancellationToken) in D:\Sourcecode\Github\Trakt.NET\Source\Lib\Trakt.NET\Requests\Handler\ResponseErrorHandler.cs:line 64
   at TraktNet.Requests.Handler.ResponseErrorHandler.HandleErrorsAsync(ExtendedHttpRequestMessage requestMessage, HttpResponseMessage responseMessage, Boolean isCheckinRequest, Boolean isDeviceRequest, Boolean isInAuthorizationPolling, Boolean isAuthorizationRequest, Boolean isAuthorizationRevoke, CancellationToken cancellationToken) in D:\Sourcecode\Github\Trakt.NET\Source\Lib\Trakt.NET\Requests\Handler\ResponseErrorHandler.cs:line 50
   at TraktNet.Requests.Handler.RequestHandler.ExecuteRequestAsync(ExtendedHttpRequestMessage requestMessage, Boolean isCheckinRequest, CancellationToken cancellationToken) in D:\Sourcecode\Github\Trakt.NET\Source\Lib\Trakt.NET\Requests\Handler\RequestHandler.cs:line 277
   at TraktNet.Requests.Handler.RequestHandler.QuerySingleItemAsync[TResponseContentType](ExtendedHttpRequestMessage requestMessage, Boolean isCheckinRequest, CancellationToken cancellationToken) in D:\Sourcecode\Github\Trakt.NET\Source\Lib\Trakt.NET\Requests\Handler\RequestHandler.cs:line 157
   at TraktNet.Requests.Handler.RequestHandler.ExecuteSingleItemRequestAsync[TResponseContentType,TRequestBodyType](IPostRequest`2 request, CancellationToken cancellationToken) in D:\Sourcecode\Github\Trakt.NET\Source\Lib\Trakt.NET\Requests\Handler\RequestHandler.cs:line 78
   at Listrr.Repositories.TraktListAPIRepository.AddMovies(IEnumerable`1 movies, TraktList list) in D:\Sourcecode\PrivateFlix.Club\Listrr\Listrr\Repositories\TraktListAPIRepository.cs:line 196
   at Listrr.Services.TraktService.AddMovies(IEnumerable`1 movies, TraktList list) in D:\Sourcecode\PrivateFlix.Club\Listrr\Listrr\Services\TraktService.cs:line 26
   at Listrr.Jobs.BackgroundJobs.ProcessListBackgroundJob.Execute(UInt32 param) in D:\Sourcecode\PrivateFlix.Club\Listrr\Listrr\Jobs\BackgroundJobs\ProcessListBackgroundJob.cs:line 28
```

I copied the JSON that is sent to the API, and sent it with postman myself. The request got an 201 Created response.

**Comment by henrikfroehling** [comment]
@TheUltimateC0der Hi, can you please provide a simple example on how to reproduce this behavior and also stack trace?

**Comment by TheUltimateC0der** [comment]
You can see the code i am using here: 
https://github.com/TheUltimateC0der/Listrr/blob/a65b5cd70ce15bce555b8a0d70718b868bef4cd8/Listrr/Repositories/TraktListAPIRepository.cs#L184

The stacktrace is the one above.

**Comment by henrikfroehling** [comment]
@TheUltimateC0der Could you please test this with the current release-1.0.0-preview deployment items?
https://dev.azure.com/henrikfroehling/Trakt.NET/_build/results?buildId=139&view=results
Just download the artifacts via the blue button in the top right corner. It's a ZIP containing the library dll and also the NuGet package.

Does this error still occur with the deployment items?

**Comment by TheUltimateC0der** [comment]
You fixed the issue mentioned in https://github.com/henrikfroehling/Trakt.NET/issues/61. The items now get added to the list properly.

However the request `TraktClient.Users.AddCustomListItemsAsync` still ends up with this response:
```
TraktNet.Exceptions.TraktBadRequestException
Bad Request - request couldn't be parsed

TraktNet.Exceptions.TraktBadRequestException: Bad Request - request couldn't be parsed
   at TraktNet.Requests.Handler.ResponseErrorHandler.HandleBadRequestError(ResponseErrorParameters errorParameters) in D:\Sourcecode\Github\Trakt.NET\Source\Lib\Trakt.NET\Requests\Handler\ResponseErrorHandler.cs:line 304
   at TraktNet.Requests.Handler.ResponseErrorHandler.HandleErrorsAsync(ResponseErrorParameters errorParameters, CancellationToken cancellationToken) in D:\Sourcecode\Github\Trakt.NET\Source\Lib\Trakt.NET\Requests\Handler\ResponseErrorHandler.cs:line 64
   at TraktNet.Requests.Handler.ResponseErrorHandler.HandleErrorsAsync(ExtendedHttpRequestMessage requestMessage, HttpResponseMessage responseMessage, Boolean isCheckinRequest, Boolean isDeviceRequest, Boolean isInAuthorizationPolling, Boolean isAuthorizationRequest, Boolean isAuthorizationRevoke, CancellationToken cancellationToken) in D:\Sourcecode\Github\Trakt.NET\Source\Lib\Trakt.NET\Requests\Handler\ResponseErrorHandler.cs:line 50
   at TraktNet.Requests.Handler.RequestHandler.ExecuteRequestAsync(ExtendedHttpRequestMessage requestMessage, Boolean isCheckinRequest, CancellationToken cancellationToken) in D:\Sourcecode\Github\Trakt.NET\Source\Lib\Trakt.NET\Requests\Handler\RequestHandler.cs:line 273
   at TraktNet.Requests.Handler.RequestHandler.QuerySingleItemAsync[TResponseContentType](ExtendedHttpRequestMessage requestMessage, Boolean isCheckinRequest, CancellationToken cancellationToken) in D:\Sourcecode\Github\Trakt.NET\Source\Lib\Trakt.NET\Requests\Handler\RequestHandler.cs:line 153
   at TraktNet.Requests.Handler.RequestHandler.ExecuteSingleItemRequestAsync[TResponseContentType,TRequestBodyType](IPostRequest`2 request, CancellationToken cancellationToken) in D:\Sourcecode\Github\Trakt.NET\Source\Lib\Trakt.NET\Requests\Handler\RequestHandler.cs:line 74
   at Listrr.Repositories.TraktListAPIRepository.AddMovies(IEnumerable`1 movies, TraktList list) in D:\Sourcecode\PrivateFlix.Club\Listrr\Listrr\Repositories\TraktListAPIRepository.cs:line 190
   at Listrr.Services.TraktService.AddMovies(IEnumerable`1 movies, TraktList list) in D:\Sourcecode\PrivateFlix.Club\Listrr\Listrr\Services\TraktService.cs:line 26
   at Listrr.Jobs.BackgroundJobs.ProcessListBackgroundJob.Execute(UInt32 param) in D:\Sourcecode\PrivateFlix.Club\Listrr\Listrr\Jobs\BackgroundJobs\ProcessListBackgroundJob.cs:line 28
```

**Comment by TheUltimateC0der** [comment]
Further debugging shows you use the wrong endpoint for this request.

Actual endpoint: `https://api.trakt.tv/users/{USERNAME}/lists/{LISTSLUGORID}/items/movies`
Expected endpoint: `https://api.trakt.tv/users/{USERNAME}/lists/{LISTSLUGORID}/items`

Reference: https://trakt.docs.apiary.io/#reference/users/add-list-items/add-items-to-custom-list

**Comment by TheUltimateC0der** [comment]
You have to remove `{/type}` from here https://github.com/henrikfroehling/Trakt.NET/blob/87efcb7de6d738a3f7a9bf734873bc718fda4691/Source/Lib/Trakt.NET/Requests/Users/OAuth/UserCustomListItemsAddRequest.cs#L19

**Comment by henrikfroehling** [comment]
@TheUltimateC0der Does this error still occur with the following NuGet package: https://dev.azure.com/henrikfroehling/_apis/resources/Containers/6809242?itemPath=Trakt.NET.142-DeploymentItems%2FTrakt.NET.1.0.0-preview.142.nupkg ?

**Comment by TheUltimateC0der** [comment]
I can confirm it works
